# Generated by Django 4.2.10 on 2024-02-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailvideos', '0001_initial'),
        ('payment_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailvideos.video'),
        ),
    ]
