# -*- coding: utf-8 -*-
# Generated by Django 4.2.9 on 2024-01-18 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment_page", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentpage",
            name="body",
        ),
        migrations.RemoveField(
            model_name="paymentpage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="paymentpage",
            name="video",
        ),
    ]
