# Generated by Django 4.2.9 on 2024-01-18 17:16

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('payment_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpage',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentpage',
            name='subtitle_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentpage',
            name='subtitle_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentpage',
            name='body',
            field=wagtail.fields.StreamField([('tab_block', wagtail.blocks.StreamBlock([('tab', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('subtitle', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('tab_item_description', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock())]), max_num=3))]))]))], use_json_field=True),
        ),
    ]
