# -*- coding: utf-8 -*-
# Generated by Django 4.2.9 on 2024-01-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentpage",
            name="subtitle",
            field=models.CharField(default="hello", max_length=255),
            preserve_default=False,
        ),
    ]
