# -*- coding: utf-8 -*-
# Generated by Django 4.2.9 on 2024-01-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_page", "0002_remove_paymentpage_body_remove_paymentpage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentpage",
            name="subtitle",
            field=models.CharField(default="hello", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentpage",
            name="subtitle_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paymentpage",
            name="subtitle_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paymentpage",
            name="subtitle_uk",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
