# -*- coding: utf-8 -*-
# Generated by Django 4.2.9 on 2024-01-18 15:03

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailvideos", "0002_alter_video_thumbnail"),
        ("payment_page", "0003_paymentpage_subtitle_paymentpage_subtitle_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "tab_block",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "tab",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("title", wagtail.blocks.CharBlock()),
                                            ("subtitle", wagtail.blocks.CharBlock()),
                                            ("image", wagtail.images.blocks.ImageChooserBlock()),
                                            (
                                                "tab_item_description",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "description",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    ("title", wagtail.blocks.CharBlock()),
                                                                    ("description", wagtail.blocks.RichTextBlock()),
                                                                    ("icon", wagtail.images.blocks.ImageChooserBlock()),
                                                                ],
                                                            ),
                                                        ),
                                                    ],
                                                ),
                                            ),
                                        ],
                                    ),
                                ),
                            ],
                        ),
                    ),
                ],
                default="he",
                use_json_field=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="paymentpage",
            name="video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailvideos.video",
            ),
        ),
    ]
