# -*- coding: utf-8 -*-
# Generated by Django 4.2.9 on 2024-01-18 16:40

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment_page", "0005_alter_paymentpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "tab_block",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "tab",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("title", wagtail.blocks.CharBlock()),
                                            ("subtitle", wagtail.blocks.CharBlock()),
                                            ("image", wagtail.images.blocks.ImageChooserBlock()),
                                            (
                                                "tab_item_description",
                                                wagtail.blocks.ListBlock(
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            ("title", wagtail.blocks.CharBlock()),
                                                            ("description", wagtail.blocks.RichTextBlock()),
                                                            ("icon", wagtail.images.blocks.ImageChooserBlock()),
                                                        ],
                                                    ),
                                                    max_num=3,
                                                ),
                                            ),
                                        ],
                                    ),
                                ),
                            ],
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
