# -*- coding: utf-8 -*-
# Generated by Django 4.2.9 on 2024-02-06 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("payment_page", "0005_alter_paymentpage_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentpage",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
