# -*- coding: utf-8 -*-
# Generated by Django 4.2.9 on 2024-02-20 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("privacy_policy_page", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privacypolicypage",
            name="page_title",
        ),
        migrations.RemoveField(
            model_name="privacypolicypage",
            name="page_title_en",
        ),
        migrations.RemoveField(
            model_name="privacypolicypage",
            name="page_title_ru",
        ),
        migrations.RemoveField(
            model_name="privacypolicypage",
            name="page_title_uk",
        ),
    ]
