# Generated by Django 4.2.10 on 2024-02-26 10:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='description_en',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('title', wagtail.blocks.RichTextBlock()), ('description', wagtail.blocks.RichTextBlock())]))], null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='postpage',
            name='description_ru',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('title', wagtail.blocks.RichTextBlock()), ('description', wagtail.blocks.RichTextBlock())]))], null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='postpage',
            name='description_uk',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('title', wagtail.blocks.RichTextBlock()), ('description', wagtail.blocks.RichTextBlock())]))], null=True, use_json_field=True),
        ),
    ]
