# Generated by Django 4.2.10 on 2024-02-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0002_postpage_description_en_postpage_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='description_uk',
        ),
        migrations.AddField(
            model_name='postpage',
            name='main_title_en',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='postpage',
            name='main_title_ru',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='postpage',
            name='main_title_uk',
            field=models.CharField(null=True),
        ),
    ]
