# -*- coding: utf-8 -*-
# Generated by Django 4.2.4 on 2023-10-26 10:30

from django.db import migrations, models

import src.wagtailvideos.models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailvideos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=src.wagtailvideos.models.get_upload_to,
                verbose_name="thumbnail",
            ),
        ),
    ]
