# -*- coding: utf-8 -*-
# Generated by Django 4.2.9 on 2024-02-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="images", verbose_name="Avatar"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=255, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(default="admin", max_length=255, verbose_name="Full name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="legal_address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Legal address"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="legal_city",
            field=models.CharField(blank=True, max_length=255, verbose_name="Legal city"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="legal_country",
            field=models.CharField(blank=True, max_length=255, verbose_name="Legal country"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, verbose_name="Phone number"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="postal_code",
            field=models.CharField(blank=True, max_length=255, verbose_name="Postal code"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="region",
            field=models.CharField(blank=True, max_length=255, verbose_name="Region"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="requisites",
            field=models.CharField(blank=True, max_length=255, verbose_name="Requisites"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(blank=True, max_length=255, verbose_name="User type"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, max_length=255, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
