# -*- coding: utf-8 -*-
# Generated by Django 4.2.9 on 2024-02-06 09:23

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="subtitle_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subtitle_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subtitle_uk",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "units_block",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "unit_item",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("value", wagtail.blocks.IntegerBlock()),
                                            ("measure_unit", wagtail.blocks.CharBlock()),
                                            ("title", wagtail.blocks.CharBlock()),
                                        ],
                                    ),
                                ),
                            ],
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
