# -*- coding: utf-8 -*-
# Generated by Django 4.2.9 on 2024-01-18 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0090_page_search_description_en_and_more"),
        ("contact_settings", "0002_rename_contactsettings_contactsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsetting",
            name="site",
            field=models.OneToOneField(
                default="",
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtailcore.site",
            ),
            preserve_default=False,
        ),
    ]
