# -*- coding: utf-8 -*-
# Generated by Django 4.2.9 on 2024-01-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_settings", "0003_headersetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="headersetting",
            name="header_discount",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
