# -*- coding: utf-8 -*-
# Generated by Django 4.2.9 on 2024-02-15 10:16

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models

import src.wagtailvideos.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("gallery_page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerypage",
            name="gallery_subtitle",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="gallery_title",
            field=models.CharField(default="a", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gallerypage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "gallery",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                                    ("video", src.wagtailvideos.blocks.VideoChooserBlock(required=False)),
                                    ("title", wagtail.blocks.CharBlock(max_length=200)),
                                    ("subtitle", wagtail.blocks.CharBlock(max_length=200)),
                                ],
                            ),
                            template="base/gallery_list.html",
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
